#+hugo_base_dir: ~/Documents/chop-ink/
#+hugo_section: .
#+hugo_tags: about me
#+hugo_custom_front_matter: :cover /choptr-avatar.jpg
#+hugo_custom_front_matter: :images /choptr-avatar.jpg

#+TITLE: About Me
#+AUTHOR: Chop Tr (chop.ink)

Hi, Nice to meet you.

The name is Quang Tran ~aka Chop Tr~.

I am a full-stack software engineer based in Ho Chi Minh City, Vietnam.

- I design and code simple things and I really enjoy what I do

- I love to learn new things and try out new knowledge

- I'm a minimalist


* Skills

- Javascript and Front-end Frameworks master (Vue, React, Angular)

- Firebase and Go lang lover

- GCP and Kubernetes sailor

- Functional Programing and Domain-Driven Design practitioner

- Python scriptor

- Haskell/Rust learner

- Hugo site builder

- Emacs / Vim (I love both)


* Personal life

This year, 2022, I am 33 years old. I have a beautiful wife and a lovely daughter.

I love to travel with my wife. Every year we visit new places in Vietnam. We have never traveled outside Vietnam, but love to do it one day when Lina is a bit older and the world have Covid-19 a bit under control.

I love watching movies and contemplate the philosophy aspect of the art.

I have a Raspberry Pi and use Plesk as media server.

I run a Cardano relay on AWS.

I play Chess at 900 point level. Play Starcraft at Gold league.
